function [ShortestPathsMat,numShortestPaths]=findallshortestpaths(G,kPaths,s,d)
% This function returns all the first k shortest paths and store them in a matrix
% G is the graph generated by matlab
% s: source node
% d: desdination node
% G=GraphWaterInitial
CostMatrix=adjacency(G);
CostMatrix=full(CostMatrix);
% In CostMatrix, cost of 'inf' represents the 'absence' of a link 
CostMatrix(CostMatrix==0)=inf;

% [shortestPath, totalCost]=dijkstra(CostMatrix, s, d);
[shortestPaths, totalCosts] = kShortestPath(CostMatrix, s, d, kPaths);

% find the shortest path
ShortestDist=min(totalCosts)+1;
numShortestPaths=sum(totalCosts==min(totalCosts));
if numShortestPaths==kPaths
    errordlg('Not all shortst paths have been selected. Consider increase kPaths','Error');
end
ShortestPathsMat=reshape(([shortestPaths{1,1:numShortestPaths}]),ShortestDist,[])'; % vec2mat (,nColumn) without transpose

% if another path has the same length put it into the matrix

    