function [fitresult, gof] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'fit user-defined function' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jul-2019 17:20:48


%% Fit: 'fit user-defined function'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'exp(A*x)*(B/(A + k) + C/A + 1) - exp(A*x)*((C*exp(-A*x))/A + (B*exp(-A*x)*exp(-k*x))/(A + k))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0357116785741896 0.849129305868777 0.933993247757551 0.678735154857773];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fit user-defined function' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'fit user-defined function', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
grid on


